### ISSUE TITLE
What theme are you using?

### ISSUE THREAD

**Issue by jacob-labs** [JamesMcCarthy79/Home-Assistant-Config#152]
@JamesMcCarthy79 What theme are you using for the transparent interface? If you are using a custom theme, could you please upload it?

**Comment by JamesMcCarthy79** [comment]
It is in the package called theme_control, already there :). This theme might need an update as there are new UI elements since then. I don't use this theme any more it is based off midnight theme so you should eb able to get the latest version of it from his github and then I can help you with what options are required to make it transparent.

**Comment by jakesie1309** [comment]
Hi James. Hope you doing well mate. Have been using midnight for almost a year and must say good theme however moving to a more modern the grey blue theme I am building out. Got inspires from dwains phone theme. Love your new look on your garden plants view. If I may ask what theme are you moving to. See you have been running midnigh for quite some time. Keep up the good work.

**Comment by JamesMcCarthy79** [comment]
Hi Jake,

I have been using my own theme for a few months now. Until this past fortnight I moved over to dwains theme. I have been busy customising addons for this theme then I'll move on to next one :)



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by jacob-labs** [comment]
Thanks James, I should've noticed that!
